// Interactive headed check: allow FrameDeck's permission prompt in this disposable test profile.
// Set PLAYWRIGHT_MODULE and CHROMIUM_PATH as for browser.cjs. No personal Chrome profile is used.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<!doctype html><title>FrameDeck effect test '+req.url+'</title><body style="background:#f7faf5;font:32px system-ui;padding:40px">FrameDeck effect test '+req.url+'</body>')});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port; const profile=fs.mkdtempSync(path.join(os.tmpdir(),'framedeck-effects-'));
const context=await chromium.launchPersistentContext(profile,{headless:false, executablePath:process.env.CHROMIUM_PATH || undefined,args:['--disable-extensions-except='+path.resolve(__dirname,'../extension'),'--load-extension='+path.resolve(__dirname,'../extension')],viewport:{width:1000,height:800}});
try{const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');const extension=worker.url().replace('/background.js','/popup.html');const a=await context.newPage();await a.goto(base+'/one');const b=await context.newPage();await b.goto(base+'/two');const ui=await context.newPage();await ui.goto(extension);await ui.locator('#optionsPanel summary').click();await ui.locator('#countdownToggle').check();console.log('PERMISSION PROMPT READY');
const end=Date.now()+180000;while(Date.now()<end){if(await ui.evaluate(()=>chrome.permissions.contains({origins:['http://*/*','https://*/*']})))break;await new Promise(r=>setTimeout(r,1000));}
if(!(await ui.evaluate(()=>chrome.permissions.contains({origins:['http://*/*','https://*/*']}))))throw Error('Permission not granted');
await ui.locator('#transitionsToggle').check();await ui.locator('#optionsPanel summary').click();await ui.locator('#startBtn').click();await new Promise(r=>setTimeout(r,400));
await a.waitForSelector('#framedeck-overlay');console.log('GRANT AND INJECTION PASS',await a.locator('#framedeck-overlay #time').textContent());
const before=await ui.evaluate(()=>chrome.runtime.sendMessage({action:'get-state'}));await a.reload();await a.waitForSelector('#framedeck-overlay');const after=await ui.evaluate(()=>chrome.runtime.sendMessage({action:'get-state'}));if(before.deadline!==after.deadline)throw Error('Reload reset clock');
await ui.locator('#nextBtn').click();await b.waitForSelector('#framedeck-overlay');await new Promise(r=>setTimeout(r,800));if(await a.locator('#framedeck-overlay').count())throw Error('Old page retained overlay');console.log('RELOAD, NEXT, FADE CLEANUP PASS');
await ui.locator('#optionsPanel summary').click();await ui.locator('#revokeAccessBtn').click();await new Promise(r=>setTimeout(r,300));if(await b.locator('#framedeck-overlay').count())throw Error('Revoke retained overlay');if(await ui.evaluate(()=>chrome.permissions.contains({origins:['http://*/*','https://*/*']})))throw Error('Revoke failed');console.log('REVOKE PASS');await ui.locator('#stopBtn').click();
fs.writeFileSync(path.resolve(__dirname,'../artifacts/native-effects-results.json'),JSON.stringify({passed:true,browser:context.browser().version(),date:new Date().toISOString(),checks:['native grant','real injection','reload deadline','next fade cleanup','permission revoke']},null,2));
}finally{await context.close();server.close();fs.rmSync(profile,{recursive:true,force:true});}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
